import * as stylex from "@stylexjs/stylex";
import { colors, media } from "../ui/tokens.stylex";

export const styles = stylex.create({
  overlay: { position: "fixed", inset: 0, zIndex: 40, backgroundColor: "#00000055" },
  modal: {
    position: "fixed",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    zIndex: 41,
    width: "min(720px, calc(100vw - 32px))",
    maxHeight: "min(860px, calc(100dvh - 32px))",
    height: { default: "auto", ":has(form)": "min(800px, calc(100dvh - 32px))" },
    display: "flex",
    flexDirection: "column",
    backgroundColor: colors.background,
    color: colors.foreground,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: 10,
    outline: "none",
    boxShadow: "0 20px 80px #00000025",
  },
  header: {
    flexShrink: 0,
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 16,
    padding: { default: 24, [media.mobile]: 20 },
    paddingBottom: 18,
  },
  title: { fontSize: 22, fontWeight: 550, letterSpacing: "-0.03em", margin: 0 },
  subtitle: { fontSize: 13, color: colors.muted, marginTop: 6, marginBottom: 0, lineHeight: 1.5 },
  body: {
    flex: "1 1 auto",
    containerType: "inline-size",
    containerName: "model-settings",
    padding: { default: 24, [media.mobile]: 16 },
    paddingTop: 0,
    overflowY: "auto",
    overscrollBehavior: "contain",
    scrollbarWidth: "thin",
    scrollPaddingBlock: 16,
    minHeight: 0,
  },
  sectionTitle: {
    fontSize: 12,
    color: colors.muted,
    fontWeight: 500,
    marginTop: 20,
    marginBottom: 10,
  },
  providers: {
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(2,minmax(0,1fr))",
      "@container model-settings (min-width: 630px)": "repeat(4,minmax(0,1fr))",
    },
    gap: 8,
    marginBottom: 22,
  },
  provider: {
    flexDirection: { default: "column", "@container model-settings (min-width: 360px)": "row" },
    paddingInline: 8,
    paddingBlock: 12,
    minHeight: 48,
    color: colors.foreground,
    fontSize: 12,
    lineHeight: "16px",
    textAlign: "center",
  },
  selected: { borderColor: colors.accentText, backgroundColor: colors.surface },
  fieldset: { borderWidth: 0, padding: 0, margin: 0, minWidth: 0 },
  field: { display: "grid", gap: 7, minWidth: 0, marginBottom: 16 },
  label: { fontSize: 13, fontWeight: 500 },
  input: {
    width: "100%",
    minWidth: 0,
    minHeight: 44,
    padding: 11,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: 6,
    backgroundColor: colors.surface,
    color: colors.foreground,
    fontSize: { default: 14, [media.mobile]: 16 },
  },
  inputRow: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: 8,
    alignItems: "center",
  },
  actions: { display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap", marginTop: 16 },
  modelAction: { minWidth: 104 },
  hint: { fontSize: 12, color: colors.muted, lineHeight: 1.5, margin: 0 },
  footer: {
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    gap: 12,
    justifyContent: "space-between",
    padding: { default: 24, [media.mobile]: 16 },
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: colors.border,
  },
  saved: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    paddingBlock: 10,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
  },
  savedChoice: {
    display: "flex",
    flex: 1,
    alignItems: "center",
    gap: 12,
    minWidth: 0,
    textAlign: "left",
    padding: 4,
    borderWidth: 0,
    backgroundColor: "transparent",
    color: colors.foreground,
    cursor: "pointer",
    minHeight: 44,
  },
  savedText: { display: "grid", gap: 3, minWidth: 0, fontSize: 13, overflowWrap: "anywhere" },
  modelName: {
    color: colors.muted,
    fontSize: 12,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  trigger: { gridArea: "model", justifySelf: "start", maxWidth: "min(210px, 100%)", minWidth: 0 },
  triggerText: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    maxWidth: { default: 160, [media.mobile]: 100 },
  },
  note: {
    display: "flex",
    gap: 8,
    alignItems: "flex-start",
    padding: 12,
    backgroundColor: colors.surface,
    borderRadius: 6,
    marginBottom: 18,
  },
  advanced: { fontSize: 12, color: colors.muted, marginBottom: 18 },
  summary: { cursor: "pointer", minHeight: 44, display: "flex", alignItems: "center" },
  hidden: { display: "none" },
});
