export const brandColors = {
  accentMuted: "#fdecef",
  black: "#000000",
  border: "#eaeaea",
  borderDark: "#333333",
  crimson: "#e0364b",
  crimsonBright: "#f25a6d",
  crimsonMutedDark: "#2f1118",
  darkCanvas: "#0a0a0a",
  darkBorder: "#2a2a2a",
  darkDivider: "#1f1f1f",
  darkMuted: "#7c7a76",
  darkRoleMuted: "#3a3a3a",
  darkSurface: "#111111",
  darkText: "#b4b2ae",
  darkPillText: "#c9c7c3",
  darkTextStrong: "#f2f0ec",
  foreground: "#171717",
  foregroundDark: "#ededed",
  ink: "#111111",
  labelBorder: "#e4e4e4",
  labelMuted: "#8a8884",
  labelSeparator: "#c0beb8",
  labelSurface: "#f5f5f5",
  logoBorder: "#ecebe8",
  logoMuted: "#f2f1ed",
  muted: "#666666",
  mutedDark: "#888888",
  neutral: "#bfbfbf",
  paper: "#efeeeb",
  referenceTitle: "#1a1a1a",
  sourceHeading: "#9a9893",
  surfaceMuted: "#fafafa",
  white: "#ffffff",
} as const;

export const brandCssColorTokens = {
  light: {
    "--color-bg": brandColors.white,
    "--color-fg": brandColors.foreground,
    "--color-muted": brandColors.muted,
    "--color-border": brandColors.border,
    "--color-surface": brandColors.white,
    "--color-surface-muted": brandColors.surfaceMuted,
    "--color-code-bg": brandColors.labelSurface,
    "--color-code-fg": brandColors.foreground,
    "--color-brand-dark": brandColors.darkDivider,
    "--color-brand-crimson": brandColors.crimson,
    "--color-brand-crimson-bright": brandColors.crimsonBright,
    "--color-brand-neutral": brandColors.neutral,
    "--color-brand-paper": brandColors.paper,
    "--color-accent": "var(--color-brand-crimson)",
    "--color-accent-muted": brandColors.accentMuted,
  },
  dark: {
    "--color-bg": brandColors.black,
    "--color-fg": brandColors.foregroundDark,
    "--color-muted": brandColors.mutedDark,
    "--color-border": brandColors.borderDark,
    "--color-surface": brandColors.darkSurface,
    "--color-surface-muted": brandColors.darkCanvas,
    "--color-code-bg": brandColors.darkSurface,
    "--color-code-fg": brandColors.foregroundDark,
    "--color-accent": "var(--color-brand-crimson)",
    "--color-accent-muted": brandColors.crimsonMutedDark,
  },
} as const;

export const brandOgTheme = {
  accent: brandColors.crimson,
  coral: brandColors.crimsonBright,
  dark: brandColors.darkCanvas,
  darkBorder: brandColors.darkBorder,
  darkDivider: brandColors.darkDivider,
  darkMuted: brandColors.darkMuted,
  darkPillText: brandColors.darkPillText,
  darkRoleMuted: brandColors.darkRoleMuted,
  darkText: brandColors.darkText,
  darkTextStrong: brandColors.darkTextStrong,
  ink: brandColors.ink,
  labelBorder: brandColors.labelBorder,
  labelMuted: brandColors.labelMuted,
  labelSeparator: brandColors.labelSeparator,
  labelSurface: brandColors.labelSurface,
  referenceTitle: brandColors.referenceTitle,
  sourceHeading: brandColors.sourceHeading,
  white: brandColors.white,
} as const;

export const brandAssetTheme = {
  accent: brandColors.crimson,
  border: brandColors.logoBorder,
  dark: brandColors.darkDivider,
  darkBorder: brandColors.borderDark,
  muted: brandColors.logoMuted,
  white: brandColors.white,
} as const;

export type BrandColorName = keyof typeof brandColors;
export type BrandCssThemeMode = keyof typeof brandCssColorTokens;
export type BrandOgThemeColorName = keyof typeof brandOgTheme;
export type BrandAssetThemeColorName = keyof typeof brandAssetTheme;
