from __future__ import annotations

SOURCE_ENV = "CHARTCOACH_SOURCE"
INDEX_DIR_ENV = "CHARTCOACH_INDEX_DIR"
DEFAULT_CHROMA_DIRNAME = "chroma_db"
DEFAULT_CHROMA_TOP_K = 10
DEFAULT_DUCKDB_FILENAME = "duckdb_catalog.db"

__all__ = [
    "DEFAULT_CHROMA_DIRNAME",
    "DEFAULT_CHROMA_TOP_K",
    "DEFAULT_DUCKDB_FILENAME",
    "INDEX_DIR_ENV",
    "SOURCE_ENV",
]
