from __future__ import annotations

SOURCE_ENV = "CHARTCOACH_SOURCE"
INDEX_DIR_ENV = "CHARTCOACH_INDEX_DIR"
DEFAULT_DUCKDB_FILENAME = "duckdb_catalog.db"
DEFAULT_INDEX_TOP_K = 10
LANCE_DOCUMENT_TABLE = "catalog_documents"

__all__ = [
    "DEFAULT_DUCKDB_FILENAME",
    "DEFAULT_INDEX_TOP_K",
    "INDEX_DIR_ENV",
    "LANCE_DOCUMENT_TABLE",
    "SOURCE_ENV",
]
