from __future__ import annotations

SOURCE_ENV = "CHARTCOACH_SOURCE"
INDEX_ENV = "CHARTCOACH_INDEX"
ARTIFACT_BASE_URL_ENV = "CHARTCOACH_ARTIFACT_BASE_URL"
CACHE_DIR_ENV = "CHARTCOACH_CACHE_DIR"
DEFAULT_INDEX_TOP_K = 10
DEFAULT_CATALOG_ARTIFACT_BASE_URL = "https://artifacts.chartcoach.dev"
DEFAULT_CATALOG_DIGEST = "7cfd43ee820be252b8ae9058c4c36109a9c8415c6b3a5ff8a9127117b4a10c19"
DEFAULT_CATALOG_VERSION = "0.1.3"
LANCE_DOCUMENT_TABLE = "catalog_documents"

__all__ = [
    "ARTIFACT_BASE_URL_ENV",
    "CACHE_DIR_ENV",
    "DEFAULT_CATALOG_ARTIFACT_BASE_URL",
    "DEFAULT_CATALOG_DIGEST",
    "DEFAULT_INDEX_TOP_K",
    "DEFAULT_CATALOG_VERSION",
    "INDEX_ENV",
    "LANCE_DOCUMENT_TABLE",
    "SOURCE_ENV",
]
