import * as stylex from "@stylexjs/stylex";
import { colors, media, motion } from "../ui/tokens.stylex";

const enter = stylex.keyframes({
  from: { transform: "translateY(100%)" },
  to: { transform: "translateY(0)" },
});

const exit = stylex.keyframes({
  from: { transform: "translateY(0)" },
  to: { transform: "translateY(100%)" },
});

const fadeIn = stylex.keyframes({ from: { opacity: 0 }, to: { opacity: 1 } });

const fadeOut = stylex.keyframes({ from: { opacity: 1 }, to: { opacity: 0 } });

export const styles = stylex.create({
  panel: {
    gridRow: 1,
    gridColumn: { default: "auto", [media.chatWide]: 2 },
    minWidth: 0,
    minHeight: 0,
    padding: { default: "4px 18px", [media.chatWide]: "24px 24px 24px 8px" },
    display: "flex",
    justifyContent: { default: "flex-end", [media.chatWide]: "stretch" },
    alignItems: "flex-start",
  },
  desktop: {
    display: { default: "none", [media.chatWide]: "block" },
    width: "100%",
    minWidth: 0,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: 16,
    backgroundColor: colors.surface,
    boxShadow: "0 2px 8px #00000004",
    overflow: "hidden",
  },
  header: {
    outlineOffset: -3,
    width: "100%",
    minHeight: 56,
    paddingInline: 18,
    gap: 10,
    color: colors.foreground,
    fontSize: 14,
    fontWeight: 500,
    borderRadius: 14,
  },
  count: {
    marginLeft: "auto",
    fontSize: 12,
    fontWeight: 400,
    fontVariantNumeric: "tabular-nums",
    color: colors.muted,
  },
  closedChevron: { transform: "rotate(-90deg)" },
  summary: { color: colors.muted, fontSize: 12, marginTop: 0, marginBottom: 20, lineHeight: 1.5 },
  scroll: {
    overflowY: "auto",
    overscrollBehaviorY: "contain",
    scrollbarWidth: "thin",
    scrollbarColor: `${colors.scrollThumb} transparent`,
    maxHeight: "calc(100dvh - 180px)",
    padding: "0 18px 16px",
  },
  mobileTrigger: {
    display: { default: "inline-flex", [media.chatWide]: "none" },
    gap: 8,
    borderRadius: 24,
    paddingInline: 14,
    minHeight: 44,
    fontSize: 12,
    fontWeight: 500,
    color: colors.foreground,
    backgroundColor: {
      default: colors.navigation,
      ":hover": { default: null, [media.hover]: colors.border },
    },
  },
  mobileSummary: {
    color: colors.muted,
    fontWeight: 400,
    fontVariantNumeric: "tabular-nums",
    marginLeft: 4,
  },
  overlay: {
    position: "fixed",
    inset: 0,
    zIndex: 60,
    backgroundColor: "#00000045",
    backdropFilter: "blur(2px)",
    animationName: { default: fadeIn, ":is([data-state=closed])": fadeOut },
    animationDuration: { default: "200ms", [media.reducedMotion]: "0ms" },
  },
  sheet: {
    position: "fixed",
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 61,
    width: "min(100%, 680px)",
    marginInline: "auto",
    height: "min(86dvh, 800px)",
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    backgroundColor: colors.surface,
    color: colors.foreground,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    boxShadow: "0 -12px 60px #00000020",
    outlineStyle: "none",
    animationName: { default: enter, ":is([data-state=closed])": exit },
    animationDuration: { default: "240ms", [media.reducedMotion]: "0ms" },
    animationTimingFunction: motion.easeOut,
  },
  sheetHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexShrink: 0,
    gap: 16,
    padding: "18px 20px 16px",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
  },
  sheetTitle: { fontSize: 18, fontWeight: 550, letterSpacing: "-0.025em", margin: 0 },
  sheetDescription: {
    fontSize: 12,
    lineHeight: 1.5,
    color: colors.muted,
    marginTop: 5,
    marginBottom: 0,
  },
  sheetScroll: {
    minHeight: 0,
    flex: 1,
    overflowY: "auto",
    overscrollBehaviorY: "contain",
    paddingTop: 20,
    paddingInline: 20,
    paddingBottom: "max(24px, env(safe-area-inset-bottom))",
    scrollbarWidth: "thin",
    scrollbarColor: `${colors.scrollThumb} transparent`,
  },
  list: { minWidth: 0 },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 500,
    color: colors.muted,
    marginTop: 0,
    marginBottom: 12,
    lineHeight: 1.5,
  },
  sectionCount: { marginLeft: 6, fontVariantNumeric: "tabular-nums" },
  cards: { display: "grid", gap: 14 },
  rows: { listStyle: "none", margin: 0, padding: 0 },
  row: {
    display: "block",
    paddingBlock: 12,
    textDecoration: "none",
    color: "inherit",
    borderRadius: 4,
  },
  rowHeading: { display: "flex", alignItems: "flex-start", gap: 8 },
  rowTitle: {
    flex: 1,
    fontSize: 13,
    fontWeight: 500,
    lineHeight: 1.5,
    overflowWrap: "anywhere",
    color: {
      default: colors.foreground,
      ":hover": { default: null, [media.hover]: colors.accentText },
    },
  },
  rowArrow: { marginTop: 3, color: colors.muted },
  description: {
    display: "-webkit-box",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 3,
    overflow: "hidden",
    fontSize: 12,
    lineHeight: 1.6,
    color: colors.muted,
    marginTop: 5,
    overflowWrap: "anywhere",
  },
  read: { display: "block", fontSize: 11, color: colors.muted, marginTop: 6 },
  group: {
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: colors.border,
    marginTop: 16,
  },
  groupTrigger: {
    width: "100%",
    gap: 10,
    paddingInline: 0,
    paddingBlock: 10,
    fontSize: 12,
    fontWeight: 500,
    color: colors.muted,
  },
  empty: { fontSize: 13, lineHeight: 1.6, color: colors.muted, marginTop: 0, marginBottom: 8 },
});
