import * as stylex from "@stylexjs/stylex";
import { colors, media, motion, historyRowScope } from "../ui/tokens.stylex";

const slideIn = stylex.keyframes({
  from: { transform: "translateX(-100%)" },
  to: { transform: "translateX(0)" },
});

const slideOut = stylex.keyframes({
  from: { transform: "translateX(0)" },
  to: { transform: "translateX(-100%)" },
});

export const styles = stylex.create({
  dock: {
    display: { default: "none", [media.navigationDesktop]: "block" },
    width: 256,
    flexShrink: 0,
    overflow: "hidden",
    backgroundColor: colors.navigation,
    borderRightWidth: 1,
    borderRightStyle: "solid",
    borderRightColor: colors.border,
    transitionProperty: "width",
    transitionDuration: { default: "200ms", [media.reducedMotion]: "0ms" },
    transitionTimingFunction: motion.easeOut,
  },
  collapsed: { width: 64 },
  innerClosed: { width: 64 },
  rail: { display: "flex", flexDirection: "column", alignItems: "center", gap: 4, paddingTop: 12 },
  inner: { width: 256, height: "100%" },
  overlay: { position: "fixed", inset: 0, zIndex: 40, backgroundColor: "#00000045" },
  drawer: {
    animationName: { default: slideIn, ":is([data-state=closed])": slideOut },
    animationDuration: { default: "180ms", [media.reducedMotion]: "0ms" },
    animationTimingFunction: motion.easeOut,
    position: "fixed",
    insetBlock: 0,
    left: 0,
    zIndex: 41,
    width: "min(300px, calc(100vw - 40px))",
    backgroundColor: colors.navigation,
    color: colors.foreground,
    display: "flex",
    flexDirection: "column",
    outlineStyle: "none",
    borderRightWidth: 1,
    borderRightStyle: "solid",
    borderRightColor: colors.border,
  },
  drawerHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    paddingInline: 16,
    paddingTop: "max(12px, env(safe-area-inset-top))",
    paddingBottom: 8,
  },
  title: { fontSize: 16, fontWeight: 500, margin: 0, letterSpacing: "-0.02em" },
  list: { display: "flex", flexDirection: "column", height: "100%", minHeight: 0 },
  controls: { paddingTop: 12, paddingInline: 12, flexShrink: 0 },
  newThread: {
    justifyContent: "flex-start",
    width: "100%",
    gap: 10,
    color: colors.foreground,
    fontWeight: 500,
    paddingInline: 12,
    backgroundColor: { default: colors.surface, ":hover:enabled": colors.border },
  },
  guidelines: {
    width: "100%",
    justifyContent: "flex-start",
    paddingInline: 12,
    gap: 10,
    color: colors.muted,
    marginTop: 4,
  },
  guidelinesActive: { color: colors.foreground, backgroundColor: colors.surface, fontWeight: 500 },
  guidelinesCompact: { width: 44, justifyContent: "center", paddingInline: 8, marginTop: 0 },
  guidelineCount: {
    marginLeft: "auto",
    fontSize: 11,
    fontVariantNumeric: "tabular-nums",
    color: colors.muted,
  },
  search: { display: "block", position: "relative", marginTop: 8 },
  searchIcon: {
    position: "absolute",
    top: 15,
    left: 12,
    color: colors.muted,
    pointerEvents: "none",
  },
  input: {
    minHeight: 44,
    minWidth: 0,
    width: "100%",
    fontSize: { default: 13, [media.mobile]: 16 },
    color: colors.foreground,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: 8,
    padding: 10,
  },
  searchInput: {
    paddingLeft: 34,
    backgroundColor: "transparent",
    borderColor: "transparent",
    ":focus": { backgroundColor: colors.surface, borderColor: colors.border },
  },
  section: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 12,
    paddingLeft: 12,
  },
  sectionTitle: { margin: 0, fontSize: 12, fontWeight: 500, color: colors.muted },
  archiveToggle: { minWidth: 36, minHeight: 44 },
  scroll: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    overscrollBehavior: "contain",
    scrollbarWidth: "thin",
    paddingInline: 12,
    paddingBottom: 12,
  },
  empty: { color: colors.muted, fontSize: 13, lineHeight: 1.6, padding: 12, margin: 0 },
  item: {
    display: "flex",
    alignItems: "center",
    position: "relative",
    borderRadius: 8,
    backgroundColor: {
      default: "transparent",
      ":hover": colors.surface,
      ":is([data-active])": colors.surface,
    },
    marginBottom: 2,
  },
  open: {
    flex: 1,
    minWidth: 0,
    minHeight: 44,
    paddingInline: 12,
    paddingBlock: 8,
    textAlign: "left",
    fontSize: 13,
    color: colors.foreground,
    borderWidth: 0,
    backgroundColor: "transparent",
    cursor: "pointer",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  more: {
    opacity: {
      default: 1,
      [media.hover]: 0,
      [stylex.when.ancestor(":hover", historyRowScope)]: 1,
      [stylex.when.ancestor(":focus-within", historyRowScope)]: 1,
      [stylex.when.ancestor("[data-active]", historyRowScope)]: 1,
      ":is([data-state=open])": 1,
    },
    color: colors.muted,
    minWidth: 32,
    width: 32,
    flexShrink: 0,
    backgroundColor: {
      default: "transparent",
      ":hover": colors.border,
      ":is([data-state=open])": colors.border,
    },
  },
  menu: {
    zIndex: 60,
    minWidth: 150,
    padding: 5,
    backgroundColor: colors.surface,
    color: colors.foreground,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: 10,
    boxShadow: "0 8px 24px #00000018",
  },
  menuItem: {
    display: "flex",
    alignItems: "center",
    gap: 9,
    minHeight: 40,
    paddingInline: 10,
    fontSize: 13,
    borderRadius: 6,
    cursor: "pointer",
    outlineStyle: "none",
    backgroundColor: { default: "transparent", ":is([data-highlighted])": colors.navigation },
  },
  rename: { display: "flex", alignItems: "center", minWidth: 0, width: "100%" },
  footer: {
    flexShrink: 0,
    padding: 20,
    paddingBottom: "max(20px, env(safe-area-inset-bottom))",
    margin: 0,
    color: colors.muted,
    fontSize: 11,
  },
});
