import * as stylex from "@stylexjs/stylex";
import { colors, disclosureScope, media, motion } from "../ui/tokens.stylex";

const FLUID_DETAILS =
  "@supports (interpolate-size: allow-keywords) and selector(::details-content)";

export const styles = stylex.create({
  root: {
    marginBlock: 4,
    marginInline: 0,
    color: colors.muted,
    fontSize: 13,
    "::details-content": {
      interpolateSize: { default: null, [FLUID_DETAILS]: "allow-keywords" },
      blockSize: {
        default: null,
        [FLUID_DETAILS]: { default: 0, ":is([open])": "auto" },
      },
      opacity: { default: null, [FLUID_DETAILS]: { default: 0, ":is([open])": 1 } },
      overflow: { default: null, [FLUID_DETAILS]: "clip" },
      transitionProperty: {
        default: null,
        [FLUID_DETAILS]: "height, opacity, content-visibility",
      },
      transitionDuration: {
        default: null,
        [FLUID_DETAILS]: {
          default: motion.disclosure,
          ":has(> summary:focus-visible)": "0ms",
          [media.reducedMotion]: "0ms",
        },
      },
      transitionTimingFunction: { default: null, [FLUID_DETAILS]: motion.easeOut },
      transitionBehavior: { default: null, [FLUID_DETAILS]: "normal, normal, allow-discrete" },
    },
  },
  summary: {
    display: "grid",
    gridTemplateColumns: "16px minmax(0, 1fr) auto 14px",
    alignItems: "center",
    columnGap: 10,
    width: "100%",
    minHeight: 44,
    paddingBlock: 6,
    paddingInline: 0,
    cursor: "pointer",
    listStyleType: "none",
    borderRadius: 4,
    color: { default: null, ":hover": colors.foreground },
    "::-webkit-details-marker": { display: "none" },
  },
  label: { display: "flex", flexDirection: "column", minWidth: 0, gridColumn: "2" },
  context: {
    overflow: "hidden",
    whiteSpace: "nowrap",
    textOverflow: "ellipsis",
    color: colors.foreground,
  },
  state: { flexShrink: 0, gridColumn: "3", marginLeft: "auto", fontSize: 12 },
  chevron: {
    gridColumn: "4",
    transform: {
      default: null,
      [stylex.when.ancestor("[open]", disclosureScope)]: "rotate(90deg)",
    },
    color: { default: null, [stylex.when.ancestor("[open]", disclosureScope)]: colors.accentText },
  },
  details: {
    marginTop: 4,
    marginRight: 0,
    marginBottom: 16,
    marginLeft: 22,
    paddingBlock: 4,
    paddingRight: 0,
    paddingLeft: 16,
    borderLeftWidth: 1,
    borderLeftStyle: "solid",
    borderLeftColor: colors.border,
    overflowWrap: "anywhere",
    lineHeight: 1.6,
  },
  heading: {
    marginTop: { default: 16, ":first-child": 0 },
    marginInline: 0,
    marginBottom: 6,
    fontSize: 12,
    fontWeight: 500,
  },
  paragraph: { margin: 0 },
  foreground: { color: colors.foreground },
  pre: { fontSize: 12, whiteSpace: "pre-wrap", margin: 0, overflowWrap: "anywhere" },
  list: { listStyleType: "none", padding: 0 },
  results: { display: "grid", gap: 16, margin: 0 },
  resultTitle: { color: colors.foreground, fontSize: 14, marginBottom: 4 },
  sources: { display: "grid", gap: 8, marginTop: 8, fontSize: 12 },
  link: { color: "inherit", textDecorationLine: "inherit", textUnderlineOffset: 3 },
  method: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    color: colors.foreground,
    marginTop: 16,
    marginInline: 0,
    marginBottom: 8,
  },
  methodIcon: { color: colors.accentText },
  config: {
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr)",
    rowGap: 4,
    columnGap: 16,
    margin: 0,
    fontSize: 12,
  },
  configValue: { color: colors.foreground, margin: 0 },
  tableScroll: {
    maxWidth: "100%",
    overflowX: "auto",
    overscrollBehaviorX: "contain",
    marginBlock: 12,
    marginInline: 0,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: 6,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    textAlign: "left",
    color: colors.foreground,
    fontSize: 12,
    lineHeight: 1.5,
  },
  cell: {
    paddingBlock: 9,
    paddingInline: 12,
    verticalAlign: "top",
    minWidth: 100,
    maxWidth: 360,
    overflowWrap: "anywhere",
  },
  headerCell: { backgroundColor: colors.background, fontWeight: 500 },
  valueCell: { borderTopWidth: 1, borderTopStyle: "solid", borderTopColor: colors.border },
  columnType: {
    display: "block",
    color: colors.muted,
    fontSize: 10,
    fontWeight: 400,
    marginTop: 2,
  },
  muted: { color: colors.muted },
  schema: {
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
    paddingBottom: 12,
    marginBottom: 16,
  },
  schemaHeading: { display: "flex", flexWrap: "wrap", justifyContent: "space-between", gap: 8 },
  schemaCount: { color: colors.muted, fontWeight: 400 },
  schemaList: { marginTop: 8, marginInline: 0, marginBottom: 0 },
  schemaRow: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1fr)",
    gap: 12,
    paddingBlock: 3,
    paddingInline: 0,
  },
  schemaValue: { margin: 0, color: colors.muted },
});
