import * as stylex from "@stylexjs/stylex";
import { colors } from "../ui/tokens.stylex";

export const styles = stylex.create({
  trigger: {
    width: "100%",
    justifyContent: "space-between",
    gap: 10,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    paddingInline: 12,
    backgroundColor: colors.surface,
  },
  count: {
    marginLeft: "auto",
    color: colors.muted,
    fontSize: 12,
    fontVariantNumeric: "tabular-nums",
  },
  summary: {
    fontSize: 13,
    lineHeight: 1.5,
    minHeight: 20,
    marginTop: 14,
    marginBottom: 0,
    fontVariantNumeric: "tabular-nums",
  },
  popup: {
    zIndex: 80,
    width: "min(420px, calc(100vw - 24px))",
    maxHeight: "var(--radix-popover-content-available-height)",
    display: "flex",
    flexDirection: "column",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: colors.surface,
    color: colors.foreground,
    boxShadow: "0 12px 40px #00000020",
    overflow: "hidden",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingInline: 12,
    paddingTop: 4,
    flexShrink: 0,
  },
  title: { fontSize: 14, fontWeight: 550, margin: 0 },
  search: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginInline: 12,
    paddingLeft: 12,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: 6,
    flexShrink: 0,
  },
  input: {
    minWidth: 0,
    width: "100%",
    minHeight: 44,
    padding: 8,
    borderWidth: 0,
    backgroundColor: "transparent",
    color: colors.foreground,
    fontSize: 16,
  },
  toolbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingInline: 12,
    fontSize: 12,
    color: colors.muted,
    flexShrink: 0,
    fontVariantNumeric: "tabular-nums",
  },
  selected: { fontSize: 12, paddingInline: 8, color: colors.muted },
  active: { color: colors.accentText, fontWeight: 550 },
  viewport: { position: "relative", height: "min(320px, 40dvh)", minHeight: 80, flexShrink: 1 },
  list: { scrollbarWidth: "thin", scrollbarGutter: "stable", overscrollBehaviorY: "contain" },
  row: {
    height: 56,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
  },
  author: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    height: "100%",
    gap: 12,
    paddingInline: 12,
  },
  name: { display: "grid", gap: 3, minWidth: 0, flex: 1 },
  authorName: { fontSize: 13, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  detail: { fontSize: 11, color: colors.muted, fontVariantNumeric: "tabular-nums" },
  selectedBar: { backgroundColor: colors.accentText },
  empty: {
    position: "absolute",
    inset: 0,
    padding: 20,
    fontSize: 13,
    color: colors.muted,
    pointerEvents: "none",
  },
  footnote: {
    fontSize: 11,
    lineHeight: 1.5,
    color: colors.muted,
    padding: 12,
    margin: 0,
    flexShrink: 0,
  },
});
