import * as stylex from "@stylexjs/stylex";
import { colors, media, motion } from "../ui/tokens.stylex";

export const styles = stylex.create({
  overlay: { position: "fixed", inset: 0, backgroundColor: "#00000045", zIndex: 30 },
  panel: {
    position: "fixed",
    top: 0,
    right: 0,
    bottom: 0,
    zIndex: 31,
    width: "min(100%, 580px)",
    backgroundColor: colors.surface,
    color: colors.foreground,
    display: "flex",
    flexDirection: "column",
    boxShadow: "-12px 0 40px #00000014",
    outline: "none",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: {
      default: "max(18px, env(safe-area-inset-top))",
      [media.short]: "max(8px, env(safe-area-inset-top))",
    },
    paddingBottom: { default: 18, [media.short]: 8 },
    paddingInline: { default: 28, [media.mobile]: 20 },
    gap: 16,
  },
  title: { fontSize: 20, fontWeight: 600, letterSpacing: "-0.025em", margin: 0 },
  description: {
    fontSize: 13,
    lineHeight: 1.5,
    color: colors.muted,
    marginTop: 6,
    marginBottom: 0,
  },
  dialogDescription: { display: { default: "block", [media.short]: "none" } },
  footerNote: { display: { default: "block", [media.short]: "none" }, minHeight: 36 },
  body: {
    overflowY: "auto",
    overscrollBehavior: "contain",
    minHeight: 0,
    flex: 1,
    paddingInline: { default: 28, [media.mobile]: 20 },
    paddingBottom: 24,
    scrollbarWidth: "thin",
    scrollbarGutter: "stable",
  },
  section: { borderWidth: 0, padding: 0, margin: 0, marginTop: 28, minWidth: 0 },
  fields: { marginTop: 0 },
  legend: { fontSize: 14, fontWeight: 550, padding: 0, marginBottom: 8 },
  note: { fontSize: 12, lineHeight: 1.5, color: colors.muted, marginTop: 0, marginBottom: 12 },
  input: {
    minHeight: 44,
    width: "100%",
    minWidth: 0,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: 6,
    backgroundColor: colors.background,
    color: colors.foreground,
    paddingInline: 12,
    paddingBlock: 8,
    fontSize: 16,
  },
  author: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    minHeight: 52,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
  },
  name: { fontSize: 13, lineHeight: 1.5, overflowWrap: "anywhere", minWidth: 0 },
  count: {
    color: colors.muted,
    fontSize: 12,
    fontVariantNumeric: "tabular-nums",
    marginLeft: 7,
    flexShrink: 0,
  },
  facetLabel: { flex: 1, minWidth: 0, display: "grid", gap: 6, paddingBlock: 10 },
  barTrack: {
    display: "block",
    height: 3,
    width: "100%",
    backgroundColor: colors.border,
    overflow: "hidden",
    borderRadius: 2,
  },
  barFill: {
    display: "block",
    height: "100%",
    width: "100%",
    backgroundColor: colors.muted,
    transformOrigin: "left",
    transitionProperty: "transform",
    transitionDuration: { default: motion.control, [media.reducedMotion]: "0ms" },
    transitionTimingFunction: motion.easeOut,
  },
  barScale: (value: number) => ({ transform: `scaleX(${value})` }),
  barHeight: (value: number) => ({ height: `${Math.max(0, value) * 100}%` }),
  overview: {
    paddingBlock: { default: 16, [media.short]: 10 },
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
  },
  overviewCount: {
    fontSize: { default: 36, [media.short]: 28 },
    fontWeight: 550,
    letterSpacing: "-0.04em",
    fontVariantNumeric: "tabular-nums",
    margin: 0,
    color: colors.accentText,
  },
  overviewTotal: { fontSize: 20, color: colors.muted, fontWeight: 400, letterSpacing: "-0.02em" },
  overviewLabel: { fontSize: 14, marginTop: 4, marginBottom: 0 },
  queryStatus: { display: "flex", flexWrap: "wrap", columnGap: 12 },
  updating: {
    opacity: 0,
    transitionProperty: "opacity",
    transitionDuration: { default: motion.control, [media.reducedMotion]: "0ms" },
    transitionDelay: "0ms",
  },
  pending: { opacity: 1, transitionDelay: "400ms" },
  histogram: { display: "flex", alignItems: "end", height: 86, gap: 2, marginTop: 18 },
  histogramColumn: { height: "100%", flex: 1, minWidth: 0, display: "flex", alignItems: "end" },
  histogramBar: {
    display: "block",
    width: "100%",
    minHeight: 1,
    borderStartStartRadius: 2,
    borderStartEndRadius: 2,
    transitionProperty: "height, background-color, opacity",
    transitionDuration: { default: motion.control, [media.reducedMotion]: "0ms" },
    transitionTimingFunction: motion.easeOut,
  },
  selectedBar: { backgroundColor: colors.accentText, opacity: 0.7 },
  dimmedBar: { backgroundColor: colors.border },
  slider: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    width: "100%",
    height: 44,
    touchAction: "none",
    userSelect: "none",
  },
  sliderTrack: {
    backgroundColor: colors.border,
    position: "relative",
    flexGrow: 1,
    height: 3,
    borderRadius: 2,
  },
  sliderRange: {
    position: "absolute",
    backgroundColor: colors.accentText,
    height: "100%",
    borderRadius: 2,
  },
  sliderThumb: {
    display: "block",
    width: 22,
    height: 22,
    borderRadius: "50%",
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderStyle: "solid",
    borderColor: colors.accentText,
    cursor: "ew-resize",
    boxShadow: "0 1px 3px #00000018",
    "::after": { content: '""', position: "absolute", inset: -11 },
  },
  axis: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: 11,
    color: colors.muted,
    fontVariantNumeric: "tabular-nums",
    marginTop: -6,
    marginBottom: 16,
  },
  sourceGrid: {
    display: "grid",
    gridTemplateColumns: { default: "1fr 1fr", [media.mobile]: "1fr" },
    columnGap: 24,
  },
  explanation: {
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: colors.border,
    marginTop: 24,
  },
  disclosure: {
    cursor: "pointer",
    fontSize: 13,
    minHeight: 44,
    paddingBlock: 14,
    color: colors.muted,
  },
  matches: { listStyle: "none", padding: 0, margin: 0 },
  match: {
    fontSize: 13,
    lineHeight: 1.5,
    paddingBlock: 9,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
  },
  select: {
    minHeight: 44,
    width: 102,
    flexShrink: 0,
    color: colors.muted,
    backgroundColor: "transparent",
    borderWidth: 0,
    borderRadius: 4,
    fontSize: 13,
    paddingInline: 6,
  },
  selected: { color: colors.foreground, fontWeight: 550 },
  years: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 },
  yearLabel: { display: "grid", gap: 7, fontSize: 12, color: colors.muted },
  source: {
    display: "flex",
    alignItems: "center",
    minHeight: 44,
    gap: 10,
    fontSize: 13,
    lineHeight: 1.4,
    cursor: "pointer",
  },
  checkbox: { width: 16, height: 16, accentColor: colors.accent, flexShrink: 0, margin: 0 },
  footer: {
    flexShrink: 0,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: colors.border,
    paddingInline: { default: 28, [media.mobile]: 20 },
    paddingTop: { default: 16, [media.short]: 10 },
    paddingBottom: {
      default: "max(20px, env(safe-area-inset-bottom))",
      [media.short]: "max(12px, env(safe-area-inset-bottom))",
    },
  },
  result: {
    fontSize: { default: 16, [media.short]: 14 },
    fontWeight: 550,
    marginTop: 0,
    marginBottom: { default: 6, [media.short]: 0 },
    fontVariantNumeric: "tabular-nums",
  },
  actions: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginTop: { default: 14, [media.short]: 8 },
  },
  recovery: { display: "flex", alignItems: "center", gap: 8 },
  apply: {
    flex: 1,
    minHeight: 44,
    borderWidth: 0,
    borderRadius: 6,
    paddingBlock: 10,
    paddingInline: 12,
    backgroundColor: colors.accentText,
    color: colors.surface,
    fontWeight: 550,
    fontSize: 13,
    transform: { default: "none", ":active:enabled": "scale(0.98)" },
    transitionProperty: "transform",
    transitionDuration: { default: motion.control, [media.reducedMotion]: "0ms" },
    transitionTimingFunction: motion.easeOut,
  },
  active: { color: colors.accentText },
  selectionCount: {
    display: { default: "inline", [media.mobile]: "none" },
    fontSize: 12,
    fontVariantNumeric: "tabular-nums",
  },
  pendingApply: { opacity: { default: 1, ":disabled": 1 } },
  error: { marginTop: 8, marginBottom: 0 },
});
