import * as stylex from "@stylexjs/stylex";
import { colors, media, motion } from "../ui/tokens.stylex";

export const styles = stylex.create({
  page: {
    width: "100%",
    minWidth: 0,
    minHeight: 0,
    backgroundColor: colors.background,
    color: colors.foreground,
    display: "flex",
    flexDirection: "column",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    maxWidth: 1360,
    marginInline: "auto",
    flexWrap: "wrap",
    paddingTop: {
      default: "max(12px, env(safe-area-inset-top))",
      [media.short]: "max(8px, env(safe-area-inset-top))",
    },
    paddingBottom: { default: 12, [media.short]: 8 },
    paddingInline: { default: 28, [media.mobile]: 20 },
    gap: 16,
  },
  title: {
    fontSize: 28,
    lineHeight: 1.15,
    fontWeight: 550,
    letterSpacing: "-0.03em",
    margin: 0,
    outlineStyle: "none",
  },
  description: {
    fontSize: 13,
    lineHeight: 1.5,
    color: colors.muted,
    marginTop: 6,
    marginBottom: 0,
  },
  footerNote: { display: { default: "block", [media.short]: "none" }, marginBottom: 0 },
  body: {
    overflowY: "auto",
    overscrollBehavior: "contain",
    minHeight: 0,
    flex: 1,
    width: "100%",
    maxWidth: 1360,
    display: "flex",
    flexDirection: "column",
    marginInline: "auto",
    paddingInline: { default: 28, [media.mobile]: 20 },
    paddingBottom: 12,
    scrollbarWidth: "thin",
    scrollbarGutter: "stable",
  },
  section: { borderWidth: 0, padding: 0, margin: 0, minWidth: 0 },
  fields: {
    borderWidth: 0,
    padding: 0,
    margin: 0,
    minWidth: 0,
    display: "grid",
    gridTemplateColumns: {
      default: "minmax(0, 1fr)",
      [media.catalogWide]: "repeat(3, minmax(0, 1fr))",
    },
    columnGap: 28,
    rowGap: 28,
    flexShrink: 0,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
  },
  legend: { fontSize: 14, fontWeight: 550, padding: 0, marginBottom: 8 },
  note: { fontSize: 12, lineHeight: 1.5, color: colors.muted, marginTop: 0, marginBottom: 12 },
  input: {
    minHeight: 44,
    width: "100%",
    minWidth: 0,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: 6,
    backgroundColor: colors.background,
    color: colors.foreground,
    paddingInline: 12,
    paddingBlock: 8,
    fontSize: 16,
  },
  author: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    minHeight: 44,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
  },
  name: {
    fontSize: 13,
    lineHeight: 1.5,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    minWidth: 0,
  },
  count: {
    color: colors.muted,
    fontSize: 12,
    fontVariantNumeric: "tabular-nums",
    marginLeft: 7,
    flexShrink: 0,
  },
  facetLabel: { flex: 1, minWidth: 0, display: "grid", gap: 4, paddingBlock: 8 },
  barTrack: {
    display: "block",
    height: 3,
    width: "100%",
    backgroundColor: colors.border,
    overflow: "hidden",
    borderRadius: 2,
  },
  barFill: {
    display: "block",
    height: "100%",
    width: "100%",
    backgroundColor: colors.muted,
    transformOrigin: "left",
    transitionProperty: "transform",
    transitionDuration: { default: motion.control, [media.reducedMotion]: "0ms" },
    transitionTimingFunction: motion.easeOut,
  },
  barScale: (value: number) => ({ transform: `scaleX(${value})` }),
  barScaleY: (value: number) => ({ transform: `scaleY(${Math.max(0, value)})` }),
  histogram: { display: "flex", alignItems: "end", height: 56, gap: 2, marginTop: 12 },
  histogramColumn: { height: "100%", flex: 1, minWidth: 0, display: "flex", alignItems: "end" },
  histogramBar: {
    display: "block",
    width: "100%",
    height: "100%",
    transformOrigin: "bottom",
    borderStartStartRadius: 2,
    borderStartEndRadius: 2,
    transitionProperty: "transform, background-color, opacity",
    transitionDuration: { default: motion.control, [media.reducedMotion]: "0ms" },
    transitionTimingFunction: motion.easeOut,
  },
  selectedBar: { backgroundColor: colors.accentText, opacity: 0.7 },
  dimmedBar: { backgroundColor: colors.border },
  slider: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    width: "100%",
    height: 44,
    touchAction: "none",
    userSelect: "none",
  },
  sliderTrack: {
    backgroundColor: colors.border,
    position: "relative",
    flexGrow: 1,
    height: 3,
    borderRadius: 2,
  },
  sliderRange: {
    position: "absolute",
    backgroundColor: colors.accentText,
    height: "100%",
    borderRadius: 2,
  },
  sliderThumb: {
    display: "block",
    width: 22,
    height: 22,
    borderRadius: "50%",
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderStyle: "solid",
    borderColor: colors.accentText,
    cursor: "ew-resize",
    boxShadow: "0 1px 3px #00000018",
    "::after": { content: '""', position: "absolute", inset: -11 },
  },
  axis: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: 11,
    color: colors.muted,
    fontVariantNumeric: "tabular-nums",
    marginTop: -6,
    marginBottom: 10,
  },
  sourceGrid: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr)",
    columnGap: 24,
  },
  headerActions: { display: "flex", alignItems: "center", gap: 4 },
  help: {
    width: "min(320px, calc(100vw - 32px))",
    padding: 20,
    borderRadius: 10,
    backgroundColor: colors.surface,
    color: colors.foreground,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    boxShadow: "0 8px 28px #00000018",
    zIndex: 70,
  },
  select: {
    minHeight: 44,
    width: 88,
    flexShrink: 0,
    color: colors.muted,
    backgroundColor: "transparent",
    borderWidth: 0,
    borderRadius: 4,
    fontSize: 13,
    paddingInline: 6,
  },
  selected: { color: colors.foreground, fontWeight: 550 },
  years: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 },
  yearLabel: { display: "grid", gap: 7, fontSize: 12, color: colors.muted },
  source: {
    display: "flex",
    alignItems: "center",
    minHeight: 44,
    gap: 10,
    fontSize: 13,
    lineHeight: 1.4,
    cursor: "pointer",
  },
  checkbox: { width: 16, height: 16, accentColor: colors.accent, flexShrink: 0, margin: 0 },
  footer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 16,
    width: "100%",
    maxWidth: 1360,
    marginInline: "auto",
    flexShrink: 0,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: colors.border,
    paddingInline: { default: 28, [media.mobile]: 20 },
    paddingTop: 10,
    paddingBottom: {
      default: "max(12px, env(safe-area-inset-bottom))",
      [media.short]: "max(12px, env(safe-area-inset-bottom))",
    },
  },
  footerSummary: { flex: "1 1 260px", minWidth: 0 },
  result: {
    fontSize: { default: 16, [media.short]: 14 },
    fontWeight: 550,
    marginTop: 0,
    marginBottom: { default: 6, [media.short]: 0 },
    fontVariantNumeric: "tabular-nums",
  },
  actions: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    width: "min(100%, 340px)",
  },
  recovery: { display: "flex", alignItems: "center", gap: 8 },
  apply: {
    flex: 1,
    minHeight: 44,
    borderWidth: 0,
    borderRadius: 6,
    paddingBlock: 10,
    paddingInline: 12,
    backgroundColor: { default: colors.accentText, ":disabled": colors.navigation },
    color: { default: "#fff", ":disabled": colors.muted },
    opacity: { default: 1, ":disabled": 1 },
    fontWeight: 550,
    fontSize: 13,
    transform: { default: "none", ":active:enabled": "scale(0.98)" },
    transitionProperty: "transform",
    transitionDuration: { default: motion.control, [media.reducedMotion]: "0ms" },
    transitionTimingFunction: motion.easeOut,
  },
  pendingApply: {
    backgroundColor: { default: colors.accentText, ":disabled": colors.accentText },
    color: { default: "#fff", ":disabled": "#fff" },
    cursor: { default: "progress", ":disabled": "progress" },
  },
  error: { marginTop: 8, marginBottom: 0 },
});
