import * as stylex from "@stylexjs/stylex";
import { colors, media, motion } from "../ui/tokens.stylex";

export const styles = stylex.create({
  section: {
    marginTop: 8,
    minWidth: 0,
    flex: { default: "none", [media.catalogWide]: "1 0 164px" },
    display: "flex",
    flexDirection: "column",
  },
  header: { display: "flex", alignItems: "center", gap: 12 },
  title: { fontSize: 14, fontWeight: 550, margin: 0 },
  description: {
    fontSize: 12,
    lineHeight: 1.5,
    color: colors.muted,
    marginTop: 6,
    marginBottom: 8,
  },
  updating: {
    marginLeft: "auto",
    color: colors.muted,
    fontSize: 12,
    opacity: 0,
    transitionProperty: "opacity",
    transitionDuration: { default: motion.control, [media.reducedMotion]: "0ms" },
    transitionDelay: "0ms",
  },
  pending: { opacity: 1, transitionDelay: "400ms" },
  list: {
    listStyle: "none",
    padding: 0,
    margin: 0,
    overflowY: "auto",
    overscrollBehaviorY: "contain",
    scrollbarWidth: "thin",
    scrollbarGutter: "stable",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: 10,
    outlineOffset: 2,
  },
  item: {
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
  },
  link: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    paddingBlock: 13,
    paddingInline: 14,
    minHeight: 48,
    color: colors.foreground,
    textDecoration: "none",
    backgroundColor: {
      default: "transparent",
      ":hover": { default: null, [media.hover]: colors.navigation },
    },
    outlineOffset: -3,
  },
  name: { flex: 1, minWidth: 0, fontSize: 13, lineHeight: 1.5, overflowWrap: "anywhere" },
  arrow: { color: colors.muted },
  preview: {
    zIndex: 70,
    width: "min(420px, calc(100vw - 24px))",
    maxHeight: "var(--radix-hover-card-content-available-height)",
    overflowY: "auto",
    borderRadius: 10,
    backgroundColor: colors.surface,
    boxShadow: "0 8px 32px #00000024",
    outlineStyle: "none",
  },
  viewport: {
    position: "relative",
    height: { default: "clamp(144px, 30dvh, 280px)", [media.catalogWide]: "auto" },
    flex: { default: "none", [media.catalogWide]: "1" },
    minHeight: 80,
  },
  empty: {
    position: "absolute",
    inset: 0,
    margin: 0,
    padding: 24,
    color: colors.muted,
    fontSize: 13,
    lineHeight: 1.5,
    pointerEvents: "none",
  },
  footer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    minHeight: 26,
    flexWrap: "wrap",
    gap: 8,
    paddingTop: 6,
  },
  range: { fontSize: 12, color: colors.muted, fontVariantNumeric: "tabular-nums" },
});
