from __future__ import annotations

SOURCE_ENV = "CHARTCOACH_SOURCE"
INDEX_PROFILE_ENV = "CHARTCOACH_INDEX_PROFILE"
CATALOG_ARTIFACT_BASE_URL = "https://artifacts.chartcoach.dev"
CATALOG_ENTRY_PATH = "catalog.json"
DEFAULT_GUIDELINE_URL_TEMPLATE = "https://chartcoach.dev/guidelines/{id}"
DEFAULT_INDEX_TOP_K = 10
LANCE_DOCUMENT_TABLE = "documents"

__all__ = [
    "CATALOG_ARTIFACT_BASE_URL",
    "DEFAULT_GUIDELINE_URL_TEMPLATE",
    "DEFAULT_INDEX_TOP_K",
    "INDEX_PROFILE_ENV",
    "LANCE_DOCUMENT_TABLE",
    "SOURCE_ENV",
]
